version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
#    volumes:
#      - ./hosts:/etc/nginx/conf.d
#      - ./www:/var/www
#      - ./logs:/var/log/nginx
#    php:
##      build: ./images/php
#      build: ./docker/php
#      volumes:
#        - ./www:/var/www
#    mysql:
#      image: mysql:8
#      ports:
#        - "3306:3306"
#      volumes:
#        - ./mysql:/var/lib/mysql
#      # задаем пароль для root пользователя
#      environment:
#        MYSQL_ROOT_PASSWORD: secret